### PR TITLE
Fix #21: Move lib folder to root

### LINKED ISSUE #21: Base table or view not found: 1146 Table 'dam._db_update' doesn't exist
After installing Dokku-alt, I install DAM on Digital Ocean (fresh droplet with Ubuntu 14.04 x64) and I get the following error:
```
Bootstrapping Dokku-alt-manager
Connecting do database: OK
Updating Database: ==[ Exception_DB: Database Query Failed ]===========

Additional information:
 * pdo_error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dam._db_update' doesn't exist
 * mode: select
 * params:   * :a: dokku-alt-000.sql

 * query: select  `status` from `_db_update`  where `name` = :a
 * template: select [options] [field] [from] [table] [join] [where] [group] [having] [order] [limit]
````

Going on dam.hostname.com displays:
````
Exception_DB: Database Query Failed
Additional information:

pdo_error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dam.user' doesn't exist
mode: select
params:
query: select count(*) from `user`
template: select [options] [field] [from] [table] [join] [where] [group] [having] [order] [limit]
````
I installed dokku-alt with this command `bash -c "$(curl -fsSL https://raw.githubusercontent.com/dokku-alt/dokku-alt/master/bootstrap.sh)"` and DAM with a simple `dokku manager:install`, nothing else in between.

Have I missed something?

Thanks.
Here're more infos:
DB is empty:
```
MariaDB [dam]> show tables;
Empty set (0.00 sec)
```
Rerunning only the migration script doesn't seem to solve the issue:
```
root@hotname:~# dokku run dam "php bootstrap.php"
Bootstrapping Dokku-alt-manager
Connecting do database: OK
Updating Database: ==[ Exception_DB: Database Query Failed ]===========

Additional information:
 * pdo_error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dam._db_update' doesn't exist
 * mode: select
 * params:   * :a: dokku-alt-000.sql
```
Anything else I could try?

### PR DESCRIPTION
**Pull request by NicolasRitouet**
atk4 tries to find the class `Controller_Migrator_MySQL` under `/app/lib/Controller/Migrator/MySQL.php`, then under `/app/vendor/atk4/atk4/lib/Controller/Migrator/MySQL.php` and finally, under `/app/shared/lib/Controller/Migrator/MySQL.php`.
Since the second location exists, it's loading the default class with the default migrate() method that doesn't create the `_db_update` table.
Moving the whole `lib` folder in the root solves the issue.
I'm not familiar with your styleguide, but you get the idea, let me know if you prefer to solve the issue differently.
The other possibility could be to rename the class `Controller_Migrator_MySQL` into `Controller_Migrator_MySQL-dam` (and the file into MySQL-dam.php).

Fix #21 

```
Additional information:
 * file: Controller/Migrator/MySQL.php
 * type: php
 * attempted_locations:   * 0: /app/lib/Controller/Migrator/MySQL.php
  * 1: /app/vendor/atk4/atk4/lib/Controller/Migrator/MySQL.php
  * 2: /app/shared/lib/Controller/Migrator/MySQL.php
```

### CODE REVIEW

**Comment by NicolasRitouet** [comment]
ping @romaninsh

**Comment by jrhorn424** [comment]
:+1: Would like to see this merged.

**Comment by romaninsh** [comment]
Created branch: https://github.com/romaninsh/dokku-alt-manager/tree/pr/22

**Comment by romaninsh** [comment]
I've separately added the file into master, so closing this down.

**Pull request closed without merging**
